<?php

/**
 * @file
 * Contains nblce_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nblce_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nblce_core module.
    case 'help.page.nblce_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides core functionality for the NBLCE site.') . '</p>';
      return $output;

    default:
  }
}
