_core:
  default_config_hash: hQu_5Svi0TQ5SE3dzjC55vecrEOKTYurvK-K7IJ8oXk
admin_css: true
fx: ''
noscript: false
one_pixel: true
placeholder: ''
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: 25
  container: ''
io:
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
  enabled: false
extras: {  }
max_region_count: 0
