features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: themes/custom/nblce_lib_unb_ca/nblce-logo.png
favicon:
  use_default: true
